export const US_STATES = [
  { name: 'Alabama', slug: 'alabama', score: 65 },
  { name: 'Alaska', slug: 'alaska', score: 70 },
  { name: 'Arizona', slug: 'arizona', score: 75 },
  { name: 'Arkansas', slug: 'arkansas', score: 68 },
  { name: 'California', slug: 'california', score: 78 },
  { name: 'Colorado', slug: 'colorado', score: 72 },
  { name: 'Connecticut', slug: 'connecticut', score: 70 },
  { name: 'Delaware', slug: 'delaware', score: 70 },
  { name: 'Florida', slug: 'florida', score: 72 },
  { name: 'Georgia', slug: 'georgia', score: 70 },
  { name: 'Hawaii', slug: 'hawaii', score: 75 },
  { name: 'Idaho', slug: 'idaho', score: 68 },
  { name: 'Illinois', slug: 'illinois', score: 70 },
  { name: 'Indiana', slug: 'indiana', score: 68 },
  { name: 'Iowa', slug: 'iowa', score: 68 },
  { name: 'Kansas', slug: 'kansas', score: 68 },
  { name: 'Kentucky', slug: 'kentucky', score: 65 },
  { name: 'Louisiana', slug: 'louisiana', score: 65 },
  { name: 'Maine', slug: 'maine', score: 70 },
  { name: 'Maryland', slug: 'maryland', score: 72 },
  { name: 'Massachusetts', slug: 'massachusetts', score: 75 },
  { name: 'Michigan', slug: 'michigan', score: 70 },
  { name: 'Minnesota', slug: 'minnesota', score: 72 },
  { name: 'Mississippi', slug: 'mississippi', score: 65 },
  { name: 'Missouri', slug: 'missouri', score: 68 },
  { name: 'Montana', slug: 'montana', score: 68 },
  { name: 'Nebraska', slug: 'nebraska', score: 68 },
  { name: 'Nevada', slug: 'nevada', score: 72 },
  { name: 'New Hampshire', slug: 'new-hampshire', score: 72 },
  { name: 'New Jersey', slug: 'new-jersey', score: 72 },
  { name: 'New Mexico', slug: 'new-mexico', score: 68 },
  { name: 'New York', slug: 'new-york', score: 75 },
  { name: 'North Carolina', slug: 'north-carolina', score: 70 },
  { name: 'North Dakota', slug: 'north-dakota', score: 68 },
  { name: 'Ohio', slug: 'ohio', score: 70 },
  { name: 'Oklahoma', slug: 'oklahoma', score: 68 },
  { name: 'Oregon', slug: 'oregon', score: 75 },
  { name: 'Pennsylvania', slug: 'pennsylvania', score: 70 },
  { name: 'Rhode Island', slug: 'rhode-island', score: 72 },
  { name: 'South Carolina', slug: 'south-carolina', score: 70 },
  { name: 'South Dakota', slug: 'south-dakota', score: 68 },
  { name: 'Tennessee', slug: 'tennessee', score: 70 },
  { name: 'Texas', slug: 'texas', score: 75 },
  { name: 'Utah', slug: 'utah', score: 70 },
  { name: 'Vermont', slug: 'vermont', score: 70 },
  { name: 'Virginia', slug: 'virginia', score: 72 },
  { name: 'Washington', slug: 'washington', score: 78 },
  { name: 'West Virginia', slug: 'west-virginia', score: 65 },
  { name: 'Wisconsin', slug: 'wisconsin', score: 70 },
  { name: 'Wyoming', slug: 'wyoming', score: 68 },
];
