// app/components/ShareCard.tsx
'use client';

import { useState } from 'react';
import { Copy, Check, Share2 } from 'lucide-react';

interface ShareCardProps {
  content: string; // The AI explanation text
  topic?: string;  // Optional topic tag (e.g., "Cardiac Cycle")
}

export function ShareCard({ content, topic = "TEAS Prep" }: ShareCardProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    // We format the text to look like a "quote" with branding at the bottom
    // This is optimized for pasting into Discord or Reddit
    const shareText = `
🧠 **StudyBuddy AI Concept Summary: ${topic}**
------------------------------------------------
${content.substring(0, 280)}... ${content.length > 280 ? '(Read full explanation at StudyBuddy.live)' : ''}

------------------------------------------------
Generated by StudyBuddy AI Tutor — Unlimited TEAS 7 Help
👉 Try it free: https://studybuddy.live
    `.trim();

    try {
      await navigator.clipboard.writeText(shareText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  return (
    <div className="mt-4 border-t border-slate-100 pt-4 flex items-center justify-between">
      <div className="text-xs font-bold text-slate-400 uppercase tracking-wide flex items-center gap-1">
        <Share2 className="w-3 h-3" />
        Share this explanation
      </div>
      
      <button
        onClick={handleCopy}
        className={`
          flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm font-medium transition-all
          ${copied 
            ? 'bg-green-50 text-green-700 ring-1 ring-green-200' 
            : 'bg-slate-50 text-slate-600 hover:bg-slate-100 hover:text-teal-600'}
        `}
      >
        {copied ? (
          <>
            <Check className="w-4 h-4" />
            Copied!
          </>
        ) : (
          <>
            <Copy className="w-4 h-4" />
            Copy for Discord/Notes
          </>
        )}
      </button>
    </div>
  );
}